language: python
python:
  - "3.6"

before_install:
# to prevent setuptools conflict error with tensorflow
  - pip install -U pip setuptools

install:
  - pip install -r requirements.txt

script:
  - flake8 src
  - python setup.py test
  - rlsp res/config/agent/sample_agent.yaml res/networks/sample_network.graphml res/service_functions/abc.yaml res/config/simulator/sample_config.yaml 10 --append-test
